#ifndef STM32F4XX_COMMON_H
#define STM32F4XX_COMMON_H

#include "../utility/macros.h"

// IRQs:
#define _I(x) _JOIN3R(F4xx_, x, _IRQ)

enum F4xx_IRQ{
	_I(WWDG) = 0,
	_I(PVD),
	_I(TAMP_STAMP),
	_I(RTC_WKUP),
	_I(FLASH),
	_I(RCC),
	_I(EXTI0),
	_I(EXTI1),
	_I(EXTI2),
	_I(EXTI3),
	_I(EXTI4),
	_I(DMA1_S0),
	_I(DMA1_S1),
	_I(DMA1_S2),
	_I(DMA1_S3),
	_I(DMA1_S4),
	_I(DMA1_S5),
	_I(DMA1_S6),
	_I(ADC_1_2_3),
	_I(CAN1_TX),
	_I(CAN1_RX0),
	_I(CAN1_RX1),
	_I(CAN1_SCE),
	_I(EXTI_5_9),
	_I(TIM1_BRK_TIM9),
	_I(TIM1_UP_TIM10),
	_I(TIM1_TRG_COM_TIM11),
	_I(TIM1_CC),
	_I(TIM2),
	_I(TIM3),
	_I(TIM4),
	_I(I2C1_EV),
	_I(I2C1_ER),
	_I(I2C2_EV),
	_I(I2C2_ER),
	_I(SPI1),
	_I(SPI2),
	_I(USART1),
	_I(USART2),
	_I(USART3),
	_I(EXTI_10_15),
	_I(RTC_ALARM),
	_I(OTG_FS_WAKEUP),
	_I(TIM8_BRK_TIM12),
	_I(TIM8_UP_TIM13),
	_I(TIM8_TRG_COM_TIM14),
	_I(TIM8_CC),
	_I(DMA1_S7),
	_I(FSMC),
	_I(SDIO),
	_I(TIM5),
	_I(SPI3),
	_I(UART4),
	_I(UART5),
	_I(TIM6_DAC),
	_I(TIM7),
	_I(DMA2_S0),
	_I(DMA2_S1),
	_I(DMA2_S2),
	_I(DMA2_S3),
	_I(DMA2_S4),
	_I(ETH),
	_I(ETH_WKUP),
	_I(CAN2_TX),
	_I(CAN2_RX0),
	_I(CAN2_RX1),
	_I(CAN2_SCE),
	_I(OTG_FS),
	_I(DMA2_S5),
	_I(DMA2_S6),
	_I(DMA2_S7),
	_I(USART6),
	_I(I2C3_EV),
	_I(I2C3_ER),
	_I(OTG_HS_EP1_OUT),
	_I(OTG_HS_EP1_IN),
	_I(OTG_HS_WKUP),
	_I(OTG_HS),
	_I(DMCI),
	_I(CRYP),
	_I(HASH_RNG),
	_I(FPU),
	_I(F407_COUNT) = 82, // last IRQ tracking.
	_I(F4xx_MAX_COUNT) = 82,

};
#undef _I

#endif //STM32F4XX_COMMON_H
