import copy
import os

from stm32_regtypes import Register, RegisterAccess, RegisterBitField, RegisterPermission, STM32Chip
from stm32_headerparser import STM32HeaderParser
from stm32_fixupspec import apply_peripheral_fixup
from peripherals.adcc import ADCC_TYPE_A
from peripherals.iwdg import apply_iwdg_fixup
from peripherals.i2c import I2C_TYPE_A
from peripherals.usart import fix_usart
from peripherals.tim import TIM_TYPE_A as TIM_TYPE_A_FIXUP

from stm32f030xx import *
from stm32c092xx import *
from stm32f427xx import *
from stm32g070xx import *
from stm32h503xx import *


def global_supplemental_data(info: STM32Chip):
	apply_iwdg_fixup(info.periph_map)
	apply_peripheral_fixup(info.periph_map, "ADCC", ADCC_TYPE_A)
	apply_peripheral_fixup(info.periph_map, "I2C", I2C_TYPE_A)
	fix_usart(info.periph_map)
	apply_peripheral_fixup(info.periph_map, "TIM", TIM_TYPE_A_FIXUP)


def process_chip(info: STM32Chip):
	parser = STM32HeaderParser()
	parser.load(f"src/{info.header}")

	# Phase 1: extract typedef structs (with array expansion), addresses, IRQs
	parsed = parser.parse_registers()
	info.periph_map   = parsed.periph_map
	info.periph_addrs = parsed.periph_addrs
	info.periph_irqs  = parsed.periph_irqs
	info.not_found    = parsed.not_found

	# Post-register fixups run before bitfield parsing so injected registers
	# also get their bitfields captured in phase 2.
	info.fixups.post_register_fixups(info)

	# Phase 2: populate bitfield Pos/Msk definitions
	print("Started bitfields...")
	parser.parse_bitfields(info.periph_map, info.not_found)

	print("Not found: ", info.not_found)
	info.fixups.post_bitfield_fixups(info)
	info.fixups.supplemental_data(info)

	global_supplemental_data(info)
	info.generate_all()
	info.fixups.do_custom_gen(info)


chip_data = [
	STM32Chip(name="stm32f030", header="stm32f030xc.h", fixups=stm32f030xx, gen_list=[]),
	STM32Chip(name="stm32f427", header="stm32f427xx.h", fixups=stm32f427xx, gen_list=[]),
	STM32Chip(name="stm32g070", header="stm32g070xx.h", fixups=stm32g070xx, gen_list=[]),
	STM32Chip(name="stm32h503", header="stm32h503xx.h", fixups=stm32h503xx, gen_list=["RCC", "PWR", "ICACHE", "DMA", "FLASH"]),
	STM32Chip(name="stm32c092", header="stm32c092xx.h", fixups=stm32c092xx, gen_list=["RCC", "SYSCFG"]),
]


def _merge_periph_maps(chip_periph_list: list) -> dict:
    """Build the superset register map from all (chip, periph_map) pairs.

    Registers are merged by name: the first chip to provide a register wins its
    address and description; subsequent chips contribute any fields not yet seen.
    This produces the union of all registers and bitfields across variants."""
    merged = {}
    for _chip, periph in chip_periph_list:
        for reg_name, reg in periph.items():
            if reg_name not in merged:
                merged[reg_name] = copy.deepcopy(reg)
            else:
                existing = merged[reg_name]
                for field_name, field in reg.fields.items():
                    if field_name not in existing.fields:
                        existing.fields[field_name] = copy.deepcopy(field)
    return merged


def _write_common_header(f, type_name: str, chip_names: list):
    f.write(f"/* Common {type_name} — generated by stm32_reggen.py.\n")
    f.write(" * Do not edit this file manually!\n")
    f.write(f" * Superset across: {', '.join(chip_names)}\n")
    f.write(" */\n\n")
    f.write("#pragma once\n")


def _generate_common_index(type_name: str, merged_regs: dict, chip_names: list):
    type_lower = type_name.lower()
    with open(f"generated/common/{type_name}_index.h", "w") as f:
        _write_common_header(f, type_name, chip_names)
        f.write(f"enum stm32_{type_lower}_ri\n{{\n")
        addr_sorted = sorted(merged_regs.items(), key=lambda kv: kv[1].int_addr)
        for reg_name, reg in addr_sorted:
            ri_name = reg_name.removeprefix('NS')
            f.write(f"\tRI_{ri_name:<20} = ({reg.hex_addr:<5}/4U), /* {reg.desc} */\n")
        f.write("\tRI_END\n};\n")


def _generate_common_registers(type_name: str, merged_regs: dict, chip_names: list):
    type_lower = type_name.lower()
    with open(f"generated/common/{type_name}_registers.h", "w") as f:
        _write_common_header(f, type_name, chip_names)
        f.write("#include \"../../stm32_gen_common.h\"\n")
        f.write(f"#include \"{type_name}_index.h\"\n\n")

        addr_sorted = sorted(merged_regs.items(), key=lambda kv: kv[1].int_addr)

        for reg_name, reg in addr_sorted:
            f.write("typedef union {\n")
            f.write("\tstruct {\n")
            f.write(reg.print_fields_c())
            f.write("\t} QEMU_PACKED bits;\n")
            f.write("\tuint32_t raw;\n")
            f.write(f"}}  REGDEF_NAME(com_{type_lower},{reg_name.lower()});\n")
            f.write(f"CHECK_TYPEDEF_u32(REGDEF_NAME(com_{type_lower},{reg_name.lower()}),bits);\n\n")

        f.write("typedef union {\n")
        f.write("\tstruct {\n")
        expected_addr = 0
        for reg_name, reg in addr_sorted:
            if reg.int_addr != expected_addr:
                gap = (reg.int_addr - expected_addr) // 4
                if gap == 1:
                    f.write(f"\t\tuint32_t _reserved0x{expected_addr:X};\n")
                else:
                    f.write(f"\t\tuint32_t _reserved0x{expected_addr:X}[{gap:2}];\n")
            f.write(f"\t\tREGDEF_NAME(com_{type_lower},{reg_name.lower()}) {reg_name};\n")
            expected_addr = reg.int_addr + 4
        f.write("\t} /*QEMU_PACKED*/;\n")
        f.write(f"\tuint32_t raw[RI_END];\n")
        f.write(f"}}  REGDEF_NAME(stm32com,{type_lower});\n")
        f.write(f"QEMU_BUILD_BUG_MSG(sizeof(REGDEF_NAME(stm32com,{type_lower})) != sizeof(uint32_t)*RI_END , "
                f"\"Structure Size mismatch - expected uint32[RI_END]\");\n")
        for reg_name, reg in merged_regs.items():
            f.write(f"QEMU_BUILD_BUG_MSG(offsetof(REGDEF_NAME(stm32com,{type_lower}), {reg_name}) != {reg.int_addr}, "
                    f"\"Offset mismatch for {reg_name}\");\n")


def generate_common_all(chips: list):
    """Collect common_periph declarations across all chips, merge, and generate
    generated/common/{TYPE}_index.h and generated/common/{TYPE}_registers.h for
    each declared peripheral type."""
    type_groups: dict = {}
    for chip in chips:
        for periph_name, type_name in chip.fixups.common_periph.items():
            if periph_name not in chip.periph_map:
                continue
            type_groups.setdefault(type_name, []).append((chip, chip.periph_map[periph_name]))

    os.makedirs("generated/common", exist_ok=True)
    for type_name, chip_periph_list in sorted(type_groups.items()):
        chip_names = [c.name for c, _ in chip_periph_list]
        merged = _merge_periph_maps(chip_periph_list)
        _generate_common_index(type_name, merged, chip_names)
        _generate_common_registers(type_name, merged, chip_names)
        print(f"  common/{type_name}: {', '.join(chip_names)}")


for chip in chip_data:
	print(f"Processing {chip.name}...")
	process_chip(chip)

print("Generating common peripheral type files...")
generate_common_all(chip_data)
