from enum import Enum
from dataclasses import dataclass
from abc import ABC, abstractmethod

class RegisterPermission(Enum):
    READ_WRITE = 0
    READ_ONLY = 1
    WRITE_ONLY = 2
    RESERVED = 3

class RegisterAccess(Enum):
    BYTE = 1
    HALF_WORD = 2
    WORD = 4

class STM32Fixups(ABC):
    @staticmethod
    @abstractmethod
    def post_register_fixups(chip):
        """Method to perform fixups on the register map after it has been loaded but before bitfields are processed"""
        pass
    
    @staticmethod
    @abstractmethod
    def post_bitfield_fixups(chip):
        """Method to perform fixups on the register map after bitfields have been processed"""
        pass

    @staticmethod
    @abstractmethod
    def supplemental_data(chip):
        """Method to add additional data to the register map that cannot be extracted from the header file alone"""
        pass

    @staticmethod
    @abstractmethod
    def do_custom_gen(chip):
        """Method to manually control the generation of the output files, for items not in the "global" generation list"""
        pass

# A dataclass to store a chip name, and function pointers
# to either imported data "fixups", or functions that supply
# additional data that cannot be extracted from the header file alone.
# This allows for inputting additional data that persists even if the input header file is updated.
@dataclass
class STM32Chip:
    name: str
    name_short: str
    name_short_l: str
    header: str
    fixups: STM32Fixups
    gen_list: []
    periph_map: {}
    periph_addrs: {}
    periph_irqs: {}
    not_found: {}
    def __init__(self, name, header, fixups, gen_list):
        self.name = name
        self.name_short_l = name.replace('stm32','')
        self.name_short = self.name_short_l.upper()
        self.header = header
        self.fixups = fixups
        self.gen_list = gen_list
        self.periph_map = {}
        self.periph_addrs = {}
        self.periph_irqs = {}
        self.not_found = {}

    def write_common_headertext(self, f: object, description:str):
        f.write(f"/* This file is generated by stm32_reggen.py from {self.header}\n")
        f.write(" * Do not edit this file manually! \n")
        f.write(" * If corrections are needed, use the \n")
        f.write(" * override mechanism(s) defined to modify the parsed results \n")
        f.write(" * and re-run the script to update the file. \n")
        f.write(" *\n")
        f.write(f" * This file contains the {description} for the {self.name} series of chips. \n")
        f.write(" */\n\n")
        f.write("#pragma once\n")

    def generate_AddressTable(self):
        with open(f"generated/{self.name}/Addresses.h", "w") as f:
            self.write_common_headertext(f, "peripheral addresses") 
            f.write(f"enum {self.name}_IO {{\n")
            # Sort the addresses by value:
            # First, deduplicate since some appear both as BASE_NS and BASE:
            clean_addrs = {}
            for key,addr in self.periph_addrs.items():
                clean_addrs[key.replace('_NS','').replace('_BASE','_ADDR')] = addr
            addr_sorted = {k: v for k, v in sorted(clean_addrs.items(), key=lambda item: item[1])}
            for key,addr in addr_sorted.items():
                f.write(f"\t{self.name_short}_{key.replace('_NS','_NS').replace('_BASE','_ADDR'):<20} = 0x{addr:08X}UL,\n")
            f.write("};\n")

    def generate_IRQs(self):
    	with open(f"generated/{self.name}/IRQs.h", "w") as f:
            self.write_common_headertext(f, "interrupt request IDs")
            f.write(f"enum {self.name}_IRQ {{\n")
            for key,irq in self.periph_irqs.items():
                f.write(f"\t{self.name_short}_{key.replace('IRQn','IRQ')} = {irq},\n")
            f.write(f"\t{self.name_short}_COUNT_IRQ\n")
            f.write("};\n")

    def generate_RegAddresses(self, periph: str):
        with open(f"generated/{self.name}/{periph}_index.h", "w") as f:
            self.write_common_headertext(f, f"{periph} register indexes (offsets)")
            # First, generate the enumeration of register indexes:
            f.write(f'enum {self.name}_{periph.lower()}_ri \n')
            f.write("{\n")
            addr_sorted = {k: v for k, v in sorted(self.periph_map[periph].items(), key=lambda item: item[1].int_addr)}
            for key,reg in addr_sorted.items():
                f.write(f"\tRI_{key:<20} = ({reg.hex_addr:<5}/4U), /* {reg.desc} */\n")
            f.write(f"\tRI_END\n")
            f.write("};\n\n")

    def write_bitfields(self, f:object, periph: str):
        for key,reg in self.periph_map[periph].items():
            f.write("typedef union { \n")
            f.write(f"\tstruct {{\n")
            f.write(reg.print_fields_c())
            f.write(f"\t}} QEMU_PACKED bits;\n")
            f.write("\tuint32_t raw; \n")
            f.write(f"}}  REGDEF_NAME({self.name_short_l}_{periph.lower()},{key.lower()}); \n")
            f.write(f"CHECK_TYPEDEF_u32(REGDEF_NAME({self.name_short_l}_{periph.lower()},{key.lower()}),bits);\n\n")

    def write_metadata(self, f:object, periph: str):
        f.write(f"static const stm32_reginfo_t stm32_{self.name_short_l}_{periph.lower()}_reginfo[RI_END] = \n")
        f.write("{ \n")
        for key,reg in self.periph_map[periph].items():
            f.write(reg.print_c())
        f.write("}; \n\n")

    def write_mmap(self, f:object, periph: str):
        f.write("typedef union { \n")
        f.write(f"\tstruct {{\n")
        expected_addr = 0
        for key,reg in self.periph_map[periph].items():
            if reg.int_addr != expected_addr:
                if reg.int_addr - expected_addr == 4:
                    f.write(f"\t\tuint32_t _reserved0x{expected_addr:<X};\n")
                else:
                    f.write(f"\t\tuint32_t _reserved0x{expected_addr:<X}[{int((reg.int_addr - expected_addr)/4):>2}]; \n")
            f.write(f"\t\tREGDEF_NAME({self.name_short_l}_{periph.lower()},{key.lower()}) {key};\n")
            expected_addr = reg.int_addr + 4
        f.write(f"\t}} /*QEMU_PACKED*/;\n")
        f.write("\tuint32_t raw[RI_END]; \n")
        f.write(f"}}  REGDEF_NAME({self.name_short_l},{periph.lower()}); \n")
        f.write(f"QEMU_BUILD_BUG_MSG(sizeof(REGDEF_NAME({self.name_short_l},{periph.lower()})) != sizeof(uint32_t)*RI_END , \"Structure Size mismatch - expected uint32[RI_END]\");\n")
        for key,reg in self.periph_map[periph].items():
            f.write(f"QEMU_BUILD_BUG_MSG(offsetof(REGDEF_NAME({self.name_short_l},{periph.lower()}), {key}) != {reg.int_addr}, \"Offset mismatch for {key}\");\n")

    def generate_RegDefs(self, periph: str):
        # Now generate the actual register details:
        with open(f"generated/{self.name}/{periph}_registers.h", "w") as f:
            self.write_common_headertext(f, f"{periph} register type definitions")

            f.write("#include \"../../stm32_gen_common.h\"\n")
            f.write(f"#include \"{periph}_index.h\"\n\n\n")
            self.write_bitfields(f, periph)
            self.write_metadata(f, periph)
            self.write_mmap(f, periph)

    def generate_meta_only(self, periph: str):
        # Now generate the actual register details:
        with open(f"generated/{self.name}/{periph}_reginfo.h", "w") as f:
            self.write_common_headertext(f, f"{periph} register metadata")
            f.write("#include \"../../stm32_gen_common.h\"\n")
            self.write_metadata(f, periph)


    def generate_all(self):
        self.generate_AddressTable()
        self.generate_IRQs()
        for periph in self.gen_list:
            self.generate_RegAddresses(periph)
            self.generate_RegDefs(periph)

@dataclass
class RegisterBitField:
    name: str
    desc: str
    width: int
    shift: int
    permissions: RegisterPermission
    unimplemented: bool

    def print(self):
        print(f"\tName: {self.name}, Width: {self.width}, Shift: {self.shift}, Permissions: {self.permissions}, Unimplemented: {self.unimplemented}")

    def get_unimp(self):
        return 1 if self.unimplemented else 0



@dataclass 
class Register:
    name: str
    desc: str
    hex_addr: str
    int_addr: int
    fields: {}
    access: RegisterAccess
    reset_value: int
    unimplemented: bool = False

    def print(self):
        print(f"Name: {self.name}, Description: {self.desc}, Address: {self.hex_addr}, Access: {self.access}, Reset Value: {self.reset_value}")
        for field in self.fields:
            field.print()
    
    def get_valid_mask(self):
        mask = 0
        for c,field in self.fields.items():
            mask |= (2**field.width - 1) << field.shift
        return mask

    def get_unimp_mask(self):
        if (self.unimplemented):
            return 0xFFFFFFFF
        mask = 0
        for c,field in self.fields.items():
            if field.unimplemented:
                mask |= (2**field.width - 1) << field.shift
        return mask

    def print_fields_c(self) -> str:
        retval = ""
        
        fields_by_shift = [None] * 32
        for field in self.fields.values():
            fields_by_shift[field.shift] = field

        next = 0
        for field in fields_by_shift:
            if field is None:
                continue
            if field.shift > next:
                retval = retval + f"\t\tuint32_t _reserved{next:<5}:{field.shift - next:>2}; \n"
            retval = retval + f"\t\tuint32_t {field.name:<14}:{field.width:>2}; "
            if field.desc is not None:
                retval = retval + f"// {field.desc}"
            retval = retval + "\n"
            next = field.shift + field.width
        if next < 32:
            retval = retval + f"\t\tuint32_t _reserved{next:<5}:{32 - next:>2}; \n"
        return retval

    def print_c(self) -> str:
        valid_mask = self.get_valid_mask()
        retval = f"\t[RI_{self.name:<15}] = {{ .reset_val = 0x{self.reset_value:08X}, .not_reserved = true, .unimp_mask = 0x{self.get_unimp_mask():08X}, .mask = 0x{valid_mask:08X} }}, /* mask = 0b{valid_mask:032b} */\n"
        return retval
