from stm32_regtypes import Register, RegisterAccess, RegisterBitField, RegisterPermission, STM32Chip
import re
import dataclasses

from stm32h503xx import *

# Create a 2-level dictionary for the register map:
# top level is peripheral name, second level is register name.


periph_map = {}

reg_pattern = re.compile(r'.+uint32_t (\w+);.+/\*!<\s+(.+)\s+Address offset: (0x\w+)\s+\*/')
typedef_pattern = re.compile(r'}\s?(\w+)_TypeDef;')

def parse_register(line: str) -> Register:
	# Construct a regexp to find register name and address:
	match = reg_pattern.match(line)
	if "RESERVED" in line:
		return None
	elif match:
		#print(match.groups())
		return Register(name = match.group(1), desc=match.group(2).strip(), hex_addr = match.group(3), int_addr = int(match.group(3), 16), fields = {}, access = None, reset_value = 0)
	else:
		return None

mask2nbits = {
	1: 1,
	3: 2,
	7: 3,
	15: 4,
	31: 5,
	63: 6,
	127: 7,
	255: 8,
	511: 9,
	1023: 10,
	2047: 11,
	4095: 12,
	8191: 13,
	16383: 14,
	32767: 15,
	65535: 16,
	131071: 17,
	262143: 18,
	524287: 19,
	1048575: 20,
	2097151: 21,
	4194303: 22,
	8388607: 23,
	16777215: 24,
	33554431: 25,
	67108863: 26,
	134217727: 27,
	268435455: 28,
	536870911: 29,
	1073741823: 30,
	2147483647: 31,
	4294967295: 32
}

def generate_includes(chip: str, periph: str, src_fn: str):
	with open(f"generated/{chip}_{periph}_index.h", "w") as f:
		f.write(f"/* This file is generated by stm32_reggen.py from {src_fn}\n")
		f.write(" * Do not edit this file manually! \n")
		f.write(" * If corrections are needed, use the \n")
		f.write(" * override mechanism(s) defined to modify the parsed results \n")
		f.write(" * and re-run the script to update the file. \n")
		f.write(" *\n")
		f.write(f" * This file contains the enumeration of register indexes for the {chip} {periph} peripheral. \n")
		f.write(" */\n\n")

		chip_short = chip.replace("stm32", "")

		f.write("#pragma once\n")
		# First, generate the enumeration of register indexes:
		f.write(f'enum {chip}_{periph.lower()}_ri \n')
		f.write("{\n")
		for key,reg in periph_map[periph].items():
			f.write(f"\tRI_{key:<20} = ({reg.hex_addr:<5}/4U), /* {reg.desc} */\n")
		f.write(f"\tRI_END\n")
		f.write("};\n\n")
	# Now generate the actual register details:
	with open(f"generated/{chip}_{periph}_registers.h", "w") as f:
		f.write(f"/* This file is generated by stm32_reggen.py from {src_fn}\n")
		f.write(" * Do not edit this file manually! \n")
		f.write(" * If corrections are needed, use the \n")
		f.write(" * override mechanism(s) defined to modify the parsed results \n")
		f.write(" * and re-run the script to update the file. \n")
		f.write(" *\n")
		f.write(f" * This file contains the register details for the {chip} {periph} peripheral. \n")
		f.write(" */\n\n")

		f.write("#pragma once\n")
	
		f.write("#include \"../stm32_gen_common.h\"\n")
		f.write(f"#include \"{chip}_{periph}_index.h\"\n\n\n")
		# First, generate the enumeration of register indexes:
		for key,reg in periph_map[periph].items():
			f.write("typedef union { \n")
			f.write(f"\tstruct {{\n")
			f.write(reg.print_fields_c())
			f.write(f"\t}} QEMU_PACKED bits;\n")
			f.write("\tuint32_t raw; \n")
			f.write(f"}}  REGDEF_NAME({chip_short}_{periph.lower()},{key.lower()}); \n")
			f.write(f"CHECK_TYPEDEF_u32(REGDEF_NAME({chip_short}_{periph.lower()},{key.lower()}),bits);\n\n")
		
		f.write(f"static const stm32_reginfo_t stm32_{chip_short}_{periph.lower()}_reginfo[RI_END] = \n")
		f.write("{ \n")
		for key,reg in periph_map[periph].items():
			f.write(reg.print_c())
		f.write("}; \n\n\n")

		# lastly, generate the structure datatype:
		f.write("typedef union { \n")
		f.write(f"\tstruct {{\n")
		expected_addr = 0
		for key,reg in periph_map[periph].items():
			if reg.int_addr != expected_addr:
				if reg.int_addr - expected_addr == 4:
					f.write(f"\t\tuint32_t _reserved0x{expected_addr:<X};\n")
				else:
					f.write(f"\t\tuint32_t _reserved0x{expected_addr:<X}[{int((reg.int_addr - expected_addr)/4):>2}]; \n")
			f.write(f"\t\tREGDEF_NAME({chip_short}_{periph.lower()},{key.lower()}) {key};\n")
			expected_addr = reg.int_addr + 4
		f.write(f"\t}} /*QEMU_PACKED*/;\n")
		f.write("\tuint32_t raw[RI_END]; \n")
		f.write(f"}}  REGDEF_NAME({chip_short},{periph.lower()}); \n")
		f.write(f"QEMU_BUILD_BUG_MSG(sizeof(REGDEF_NAME({chip_short},{periph.lower()})) != sizeof(uint32_t)*RI_END , \"Structure Size mismatch - expected uint32[RI_END]\");\n")
		for key,reg in periph_map[periph].items():
			f.write(f"QEMU_BUILD_BUG_MSG(offsetof(REGDEF_NAME({chip_short},{periph.lower()}), {key}) != {reg.int_addr}, \"Offset mismatch for {key}\");\n")

not_found_regs = {}
shift_pattern = re.compile(r'\((\d+)U\)')
msk_pattern = re.compile(r'\((0x[0-9A-F]+)UL')
msk2_pattern = re.compile(r'\(([0-9]+)UL')
desc_pattern = re.compile(r'^.*?(/\*.*\*/)$')

def parse_bitfield_mask(mask: int, field: str, reg: Register):
	if mask in mask2nbits:
		reg.fields[field].width = mask2nbits[mask]
	else:
		mskstr = f"0{mask:032b}"
		cur_start = 0
		n_blocks = 0
		cur_msk = ""
		while mskstr is not "":
			if mskstr[-1] == "1":
				cur_msk += "1"
			else:
				if cur_msk is not "":
					f_start = cur_start + 1
					f_width = len(cur_msk)
					if n_blocks == 0:
						reg.fields[field].width = f_width
					else:
						f_name = f"{field}_{n_blocks}"
						reg.fields[f_name] = dataclasses.replace(reg.fields[field])
						reg.fields[f_name].name = f_name
						reg.fields[f_name].width = f_width
						reg.fields[f_name].shift += f_start
						# print("Found field: ", f_name, f_width, f_start)
						# for f,v in reg.fields.items():
						# 	v.print()
					n_blocks += 1
					cur_msk = ""
					cur_start += f_width
				else:
					cur_start += 1
			mskstr = mskstr[:-1]

def parse_bitfield_info(line: str):
	tokens = line.split()
	if len(tokens) < 3:
		return
	def_parts = tokens[1].split("_")
	if len(def_parts) < 3:
		return
	periph = def_parts[0]
	reg = def_parts[1]
	field = def_parts[2]
	if len(def_parts) > 3:
		suffix = def_parts[3]
	elif field == "Msk" or field == "Pos": #Registers with no fields
		suffix = field
		field = reg
	else:
		suffix = None

	if periph not in periph_map:
		not_found_regs[f'{periph}'] = True
		return
	elif reg not in periph_map[periph]:
		not_found_regs[f'{periph}_{reg}'] = True
		return

	if suffix == "Pos":
		shift_match = shift_pattern.match(tokens[2])
		if not shift_match:
			print("Shift not found: ", tokens[2])
			exit()
		else :
			shift = int(shift_match.group(1))
		periph_map[periph][reg].fields[field] = (RegisterBitField(name = field, desc = None, width = None, shift = shift, permissions = None, unimplemented = False))
	elif suffix == "Msk":
		msk_match = msk_pattern.match(tokens[2])
		msk2_match = msk2_pattern.match(tokens[2])
		if msk_match:
			intval = int(msk_match.group(1), 16)
			parse_bitfield_mask(intval, field, periph_map[periph][reg])
			# if intval in mask2nbits:
			# 	periph_map[periph][reg].fields[field].width = mask2nbits[intval]
			# else:
			# 	print("Mask not found: ", line)
		elif msk2_match:
			intval = int(msk2_match.group(1))
			parse_bitfield_mask(intval, field, periph_map[periph][reg])
			# if intval in mask2nbits:
			# 	periph_map[periph][reg].fields[field].width = mask2nbits[intval]
			# else:
			# 	print("Mask not found: ", line)
		else:
			print("Mask not found: ", line)
	elif suffix == None:
		desc = desc_pattern.match(line)
		if desc:
			try:
				periph_map[periph][reg].fields[field].desc = desc.group(1)
			except KeyError:
				print("Field not found: ", line)

bitfield_pattern = re.compile(r'([A-Z0-9]+)_([A-Z0-9]+)_([A-Z0-9]+)')
pos_pattern = re.compile(r'\((\d+)U\)')

def process_chip(info: STM32Chip):
	in_bitfield = False
	counter = 0
	with open(f"src/{info.header}", "r+") as f:
		for line in f:
			if not in_bitfield and "typedef struct" in line:
				tmp_dict = {}
				while "}" not in line:
					line = f.readline()
					reg = parse_register(line)
					if reg is not None:
						tmp_dict[reg.name] = reg
				match = typedef_pattern.match(line)
				if match:
					periph_map[match.group(1)] = tmp_dict
					print("Found Peripheral: ", match.group(1))
			if not in_bitfield and ("Pos" in line or "Msk" in line):
				print("Started bitfields...")
				in_bitfield = True
				if info.post_register_fixups is not None:
					info.post_register_fixups(periph_map)
			if in_bitfield:
				parse_bitfield_info(line)
		print("Not found: ", not_found_regs)
		if info.post_bitfield_fixups is not None:
			info.post_bitfield_fixups(periph_map)
		if info.supplemental_data is not None:
			info.supplemental_data(periph_map)
	generate_includes(info.name, "RCC", info.header)
	generate_includes(info.name, "PWR", info.header)
	generate_includes(info.name, "TIM", info.header)
	generate_includes(info.name, "ICACHE", info.header)


chip_data = [STM32Chip(name="stm32h503", header="stm32h503xx.h", post_register_fixups=None, post_bitfield_fixups=stm32h503xx.post_bitfield_fixups, supplemental_data=stm32h503xx.extra_data)]


for chip in chip_data:
	process_chip(chip)
